### ISSUE TITLE
branch python3 is better to update 

### ISSUE THREAD

**Issue by PeterChenYijie** [marvis/pytorch-yolo3#11]
Hi, `branch python3` does not update to fix some issues .like `Pull requests:Modified some division operators for python3`
https://github.com/marvis/pytorch-yolo3/blob/4314be77573807e3913b58c4b77e1c7d5ad0a3ef/darknet.py#L179   

use "//" instead of "/"

**Comment by marvis** [comment]
python3 branch works now.
