### ISSUE TITLE
Error with PIL: AttributeError: width

### ISSUE THREAD

**Issue by guist** [marvis/pytorch-yolo3#18]
Hello,

When I run detect.py on dog.jpg with python 2.7 and pytorch 0.3, I get the following error. 

> Traceback (most recent call last):
>   File "detect.py", line 114, in <module>
>     detect(cfgfile, weightfile, imgfile)
>   File "detect.py", line 32, in detect
>     boxes = do_detect(m, sized, 0.5, 0.4, use_cuda)
>   File "/raid5/stern/pytorch-yolo3/utils.py", line 318, in do_detect
>     width = img.width
>   File "/raid5/stern/anaconda3/envs/pytorch-yolo3/lib/python2.7/site-packages/PIL/Image.py", line 512, in __getattr__
>     raise AttributeError(name)
> AttributeError: width

I am wondering if I have the correct version of PIL. Could you please indicate the version you are using? 

Thank you!
Guillaume

**Comment by riverfan** [comment]
Hi Guillaume,

You could try to use this code to access the width+height of a PIL image:

`width, height = img.size`

Florent

**Comment by guist** [comment]
Dear Florent,

Thanks for your message. I have tried what you suggest. I could indeed retrieve the image width and height but then I got another AttributeError on the next line with the tobytes() method. 

Finally I found another solution. I tried the Python 3 version instead of the Python 2 and it worked.

Best regards,
Guillaume
