### ISSUE TITLE
Something wrong when I run detect.py

### ISSUE THREAD

**Issue by zpr1994** [marvis/pytorch-yolo3#2]
when I used the command 'python detect.py cfg/yolov3.cfg yolov3.weights data/dog.jpg'
![image](https://user-images.githubusercontent.com/36948867/38286802-de82489a-37f9-11e8-914e-1d45a53f505c.png)
then I print them like
![image](https://user-images.githubusercontent.com/36948867/38286813-f1e049fa-37f9-11e8-974b-c20079e5b76e.png)
the result is 
![image](https://user-images.githubusercontent.com/36948867/38286829-009c2c52-37fa-11e8-8ce2-b6e01ce70512.png)

is there anything that can not run on the windows?

**Comment by Swall0w** [comment]
I had same issue on macOS High Sierra version 10.13.3. Therefore I think it's not your environment problem.

**Comment by ayooshkathuria** [comment]
You should try it with Python 2.7 I guess

**Comment by CharlesPikachu** [comment]
I have the same problem.
I simply modify it by replacing '/' with '//' somewhere(utils.py and darknet.py).
code base on python2, I guess.

**Comment by marvis** [comment]
Yes, the current code is for python2
