### ISSUE TITLE
python3 version errors

### ISSUE THREAD

**Issue by hktxt** [marvis/pytorch-yolo3#34]
forked the python3 version, still got errors:
...
...
105 conv    255  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 255
  106 detection
Traceback (most recent call last):
  File "detect.py", line 114, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 12, in detect
    m.load_weights(weightfile)
  File "E:\condaDev\pytorch-yolo3-python3\darknet.py", line 334, in load_weights
    start = load_conv_bn(buf, start, model[0], model[1])
  File "E:\condaDev\pytorch-yolo3-python3\cfg.py", line 187, in load_conv_bn
    conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3

**Comment by ZhengXing-shawn** [comment]
The error occur when the Pytorch version > 0.3.1

Fix the problem by replece 
'conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w'
with 'conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w]).view(conv_model.weight.data.shape)); start = start + num_w'

Then it work well with pytorch=0.4 and pytorch=1.0
