### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by ty0803** [marvis/pytorch-yolo3#8]
Ihave this problem when I run “python detect.py cfg/yolov3.cfg yolov3.weights data/dog.jpg”。File "/home/zhao/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 89, in conv2d
    torch.backends.cudnn.deterministic, torch.backends.cudnn.enabled)
RuntimeError: argument 1 (padding) must be tuple of int but got tuple of (float, float)

**Comment by marvis** [comment]
what is the version of your python?
