### ISSUE TITLE
Error when using the giving command

### ISSUE THREAD

**Issue by GustavoWang** [marvis/pytorch-yolo3#9]
Hi, I forked your project and used wget to get the weights, then run  “python detect.py cfg/yolov3.cfg yolov3.weights data/dog.jpg”, there got an error

82 detection
   83 route  79
   84 conv    256  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x 256
   85 upsample           * 2    13 x  13 x 256   ->    27 x  27 x 256
   86 route  85 61
Traceback (most recent call last):
  File "detect.py", line 114, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 11, in detect
    m.print_network()
  File "/Users/gustavo/Python/yolo3/pytorch-yolo3/darknet.py", line 158, in print_network
    print_cfg(self.blocks)
  File "/Users/gustavo/Python/yolo3/pytorch-yolo3/cfg.py", line 134, in print_cfg
    assert(prev_width == out_widths[layers[1]])
AssertionError

**Comment by brchlluk** [comment]
I get the same error, did you find any solution?

**Comment by Wisgon** [comment]
I got the error on python3.6, but it works fine in python2.7

**Comment by marvis** [comment]
python3 branch will fix this problem.
